/************************************************************\
 **   Copyright (c) 2012-2024 Anlogic
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/dk/Desktop/AnLogic/FPGA EF2L45/al_ip/sample_memory.v
 ** Date	:	2026 01 09
 ** TD version	:	4.6.116866
\************************************************************/

`timescale 1ns / 1ps

module sample_memory ( 
	dia, addra, cea, clka,
	dob, addrb, clkb
);

	output [31:0] dob;


	input  [31:0] dia;
	input  [12:0] addra;
	input  [12:0] addrb;
	input  cea;
	input  clka;
	input  clkb;



	EF2_LOGIC_BRAM #( .DATA_WIDTH_A(32),
				.DATA_WIDTH_B(32),
				.ADDR_WIDTH_A(13),
				.ADDR_WIDTH_B(13),
				.DATA_DEPTH_A(6144),
				.DATA_DEPTH_B(6144),
				.MODE("PDPW"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("32K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({32{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.bea(1'b0),
				.web(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(),
				.dob(dob));


endmodule