/************************************************************\
 **   Copyright (c) 2012-2024 Anlogic
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/dk/Desktop/AnLogic/FPGA/al_ip/pll.v
 ** Date	:	2025 11 30
 ** TD version	:	4.6.116866
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:               50.000000Mhz
//	Clock multiplication factor: 4
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 200.000000MHZ	| 0.0000  DEG  
//		C1        	| 200.000000MHZ	| 90.0000 DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll(refclk,
		reset,
		clk0_out,
		clk1_out);

	input refclk;
	input reset;
	output clk0_out;
	output clk1_out;

	wire clk0_buf;

	AL_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	AL_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.FIN("50.000000"),
		.FEEDBK_MODE("NORMAL"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("ENABLE"),
		.GEN_BASIC_CLOCK("ENABLE"),
		.GMC_GAIN("4"),
		.ICP_CURRENT(13),
		.KVCO("4"),
		.LPF_CAPACITOR("1"),
		.LPF_RESISTOR(4),
		.REFCLK_DIV(1),
		.FBCLK_DIV(4),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(5),
		.CLKC0_CPHASE(4),
		.CLKC0_FPHASE("0"),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(5),
		.CLKC1_CPHASE(5),
		.CLKC1_FPHASE("2")	)
	pll_inst (.refclk(refclk),
		.pllreset(reset),
		.stdby(1'b0),
		.ext_lock(open),
		.load_reg(1'b0),
		.scanclk(1'b0),
		.phaseupdown(1'b0),
		.phasestep(1'b0),
		.phcntsel(3'b000),
		.phasedone(open),
		.fbclk(clk0_out),
		.clkc({open, open, open, clk1_out, clk0_buf}));

endmodule
