/************************************************************\
 **   Copyright (c) 2012-2024 Anlogic
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/dk/Desktop/AnLogic/FPGA EF2/al_ip/pll.v
 ** Date	:	2025 11 19
 ** TD version	:	4.6.116866
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:               50.000000Mhz
//	Clock multiplication factor: 20
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 200.000000MHZ	| 0.0000  DEG  
//		C1        	| 200.000000MHZ	| 90.0000 DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll(refclk,
		reset,
		clk0_out,
		clk1_out);

	input refclk;
	input reset;
	output clk0_out;
	output clk1_out;


	EF2_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.DYNCFG("DISABLE"),
		.FIN("50.000000"),
		.FEEDBK_MODE("NOCOMP"),
		.FEEDBK_PATH("VCO_PHASE_0"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN(4),
		.ICP_CURRENT(13),
		.KVCO(4),
		.LPF_CAPACITOR(1),
		.LPF_RESISTOR(4),
		.REFCLK_DIV(1),
		.FBCLK_DIV(20),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(5),
		.CLKC0_CPHASE(4),
		.CLKC0_FPHASE(0),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(5),
		.CLKC1_CPHASE(5),
		.CLKC1_FPHASE(2),
		.PU_INTP("DISABLE"),
		.INTPI(0),
		.HIGH_SPEED_EN("DISABLE"),
		.SSC_ENABLE("DISABLE"),
		.SSC_MODE("Down"),
		.SSC_AMP(0.0000),
		.SSC_FREQ_DIV(0),
		.SSC_RNGE(0),
		.FREQ_OFFSET(0.0000),
		.OFFSET_MODE("EXT"),
		.FREQ_OFFSET_INT(0),
		.CLKC0_DUTY(0.5000),
		.CLKC0_DUTY_INT(3),
		.CLKC0_DUTY50("ENABLE"),
		.CLKC1_DUTY(0.5000),
		.CLKC1_DUTY_INT(3),
		.CLKC1_DUTY50("ENABLE")	)
	pll_inst (.refclk(refclk),
		.reset(reset),
		.stdby(1'b0),
		.extlock(open),
		.load_reg(1'b0),
		.psclk(1'b0),
		.psdown(1'b0),
		.psstep(1'b0),
		.psclksel(3'b000),
		.psdone(open),
		.dclk(1'b0),
		.dcs(1'b0),
		.dwe(1'b0),
		.di(8'b00000000),
		.daddr(6'b000000),
		.do({open, open, open, open, open, open, open, open}),
		.fbclk(1'b0),
		.clkc({open, open, open, open, open, clk1_out, clk0_out}),
		.ssc_en(1'b0),
		.frac_offset_valid(1'b0),
		.dsm_refclk(1'b0),
		.dsm_rst(reset));

endmodule
